version: 2
updates:
  # Maintain dependencies for Python backend
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Node/Vite frontend
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
